# Generated by Django 5.0.4 on 2025-03-07 18:07

import uuid

from django.db import migrations, models


def generate_unique_tokens(apps, schema_editor):
    Profile = apps.get_model("Users", "Profile")
    for profile in Profile.objects.all():
        profile.email_confirmation_token = uuid.uuid4()
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0002_alter_profile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_confirmation_token",
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
        migrations.RunPython(
            generate_unique_tokens, reverse_code=migrations.RunPython.noop
        ),
    ]
