# Generated by Django 5.0.4 on 2025-03-07 18:07

from django.db import migrations, models
import uuid

def generate_unique_tokens(apps, schema_editor):
    Profile = apps.get_model("Users", "Profile")  # Adjust 'Users' to your app name
    for profile in Profile.objects.all():
        if profile.email_confirmation_token is None:
            profile.email_confirmation_token = uuid.uuid4()
            profile.save()
            
class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0002_alter_profile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_confirmation_token",
            field=models.UUIDField(unique=True, blank=True, null=True),  # Allow NULL for existing records
        ),
        migrations.RunPython(generate_unique_tokens, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="profile",
            name="email_confirmation_token",
            field=models.UUIDField(unique=True, default=uuid.uuid4, editable=False),  # Remove NULL constraint
        ),
    ]