repos:
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        exclude: "^(Timely/env/|migrations/|__pycache__/|node_modules/|venv/)"
        args: ["--max-line-length=100"]  # ✅ Prevents unnecessary long line warnings
  
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3
        exclude: "^(Timely/env/|migrations/|__pycache__/|node_modules/|venv/)"
        args: ["--fast"]  # ✅ Runs Black in fast mode
        pass_filenames: false 
  
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: "^(Timely/env/|migrations/|__pycache__/|node_modules/|venv/)"
        pass_filenames: false 
  
  - repo: https://github.com/PyCQA/pylint
    rev: v3.0.3
    hooks:
      - id: pylint
        exclude: "^(Timely/env/|migrations/|__pycache__/|node_modules/|venv/)"
        args: ["--disable=C0114,C0115,C0116"]  # ✅ Disable docstring warnings
        fail_if_empty: false
  
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-r", "Timely/"]
        exclude: "^(Timely/env/|migrations/|__pycache__/|node_modules/|venv/)"
  
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports", "--follow-imports=skip", "--disallow-untyped-defs"]
        exclude: "^(Timely/env/|migrations/|__pycache__/|node_modules/|venv/)"
