# Generated by Django 5.0.4 on 2025-03-16 10:25

from django.db import migrations, models
import uuid
def generate_unique_tokens(apps, schema_editor):
    Notebook = apps.get_model("Notes", "Notebook")  # Adjust 'Users' to your app name
    for notebook in Notebook.objects.all():
        if notebook.notebook_uuid is None:
            notebook.notebook_uuid = uuid.uuid4()
            notebook.save()

class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0023_notebook_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='notebook_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(
            generate_unique_tokens, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="notebook",
            name="notebook_uuid",
            field=models.UUIDField(
                unique=True, default=uuid.uuid4, editable=False
            ),  # Remove NULL constraint
        ),
    ]
